<?php
	
	namespace Midi\Tests\Util;

	class InstrumentTest extends \PHPUnit_Framework_TestCase {
		
		public function testGetInstrumentNameThrowsInvalidArgumentException() {
			$this->setExpectedException('InvalidArgumentException');
			\Midi\Util\Instrument::getInstrumentName(-1);
		}
		
		public function testGetInstrumentName() {
			$instrumentMap = array(
				\Midi\Util\Instrument::ConcertGrand              => 'Concert Grand',
				\Midi\Util\Instrument::Piano                     => 'Piano',
				\Midi\Util\Instrument::ElectricPiano             => 'Electric Piano',
				\Midi\Util\Instrument::HonkyTonk                 => 'Honky Tonk',
				\Midi\Util\Instrument::FenderRhodesElectricPiano => 'Fender Rhodes Electric Piano',
				\Midi\Util\Instrument::PianoWithChorus           => 'Piano with Chorus',
				\Midi\Util\Instrument::Harpsichord               => 'Harpsichord',
				\Midi\Util\Instrument::HohnerClavinetD6          => 'Hohner Clavinet D6',
				\Midi\Util\Instrument::Celesta                   => 'Celesta',
				\Midi\Util\Instrument::Glockenspiel              => 'Glockenspiel',
				\Midi\Util\Instrument::MusicBox                  => 'Music Box',
				\Midi\Util\Instrument::Vibraphone                => 'Vibraphone',
				\Midi\Util\Instrument::Marimba                   => 'Marimba',
				\Midi\Util\Instrument::Xylophone                 => 'Xylophone',
				\Midi\Util\Instrument::TubularBells              => 'Tubular Bells',
				\Midi\Util\Instrument::Dulcimer                  => 'Dulcimer',
				\Midi\Util\Instrument::HammondOrgan              => 'Hammond Organ',
				\Midi\Util\Instrument::PercussiveOrgan           => 'Percussive Organ',
				\Midi\Util\Instrument::RockOrgan                 => 'Rock Organ',
				\Midi\Util\Instrument::ChurchOrgan               => 'Church Organ',
				\Midi\Util\Instrument::ReedOrgan                 => 'Reed Organ',
				\Midi\Util\Instrument::Accordion                 => 'Accordion',
				\Midi\Util\Instrument::Harmonica                 => 'Harmonica',
				\Midi\Util\Instrument::TangoAccordion            => 'Tango Accordion',
				\Midi\Util\Instrument::AcousticGuitarNylon       => 'Acoustic Guitar (nylon)',
				\Midi\Util\Instrument::AcousticGuitarSteel       => 'Acoustic Guitar (steel)',
				\Midi\Util\Instrument::ElectricGuitarJazz        => 'Electric Guitar (jazz)',
				\Midi\Util\Instrument::ElectricGuitarClean       => 'Electric Guitar (clean)',
				\Midi\Util\Instrument::ElectricGuitarMuted       => 'Electric Guitar (muted)',
				\Midi\Util\Instrument::ElectricGuitarOverdriven  => 'Electric Guitar (overdriven)',
				\Midi\Util\Instrument::ElectricGuitarDistorted   => 'Electric Guitar (distorted)',
				\Midi\Util\Instrument::GuitarHarmonics           => 'Guitar Harmonics',
				\Midi\Util\Instrument::DoubleBassFinger          => 'Double Bass (finger)',
				\Midi\Util\Instrument::ElectricBassFinger        => 'Electric Bass (finger)',
				\Midi\Util\Instrument::ElectricBassPlectrum      => 'Electric Bass (plectrum)',
				\Midi\Util\Instrument::FretlessBass              => 'Fretless Bass',
				\Midi\Util\Instrument::SlapBass1                 => 'Slap Bass 1',
				\Midi\Util\Instrument::SlapBass2                 => 'Slap Bass 2',
				\Midi\Util\Instrument::SynthesizerBass1          => 'Synthesizer Bass 1',
				\Midi\Util\Instrument::SynthesizerBass2          => 'Synthesizer Bass 2',
				\Midi\Util\Instrument::Violin                    => 'Violin',
				\Midi\Util\Instrument::Viola                     => 'Viola',
				\Midi\Util\Instrument::Cello                     => 'Cello',
				\Midi\Util\Instrument::DoubleBassBowed           => 'Double Bass (bowed)',
				\Midi\Util\Instrument::ViolinTremolo             => 'Violin (tremolo)',
				\Midi\Util\Instrument::ViolinPizzicato           => 'Violin (pizzicato)',
				\Midi\Util\Instrument::OrchestraHarp             => 'Orchestra Harp',
				\Midi\Util\Instrument::Drum                      => 'Drum',
				\Midi\Util\Instrument::StringEnsemble1           => 'String Ensemble 1',
				\Midi\Util\Instrument::StringEnsemble2           => 'String Ensemble 2',
				\Midi\Util\Instrument::SynthesizerStrings1       => 'Synthesizer Strings 1',
				\Midi\Util\Instrument::SynthesizerStrings2       => 'Synthesizer Strings 2',
				\Midi\Util\Instrument::ChoirAahs                 => 'Choir Aahs',
				\Midi\Util\Instrument::ChoirOohs                 => 'Choir Oohs',
				\Midi\Util\Instrument::SynthesizerVoice          => 'Synthesizer Voice',
				\Midi\Util\Instrument::OrchestraComplete         => 'Orchestra Complete',
				\Midi\Util\Instrument::Trumpet                   => 'Trumpet',
				\Midi\Util\Instrument::Trombone                  => 'Trombone',
				\Midi\Util\Instrument::Tuba                      => 'Tuba',
				\Midi\Util\Instrument::MutedTrumpet              => 'Muted Trumpet',
				\Midi\Util\Instrument::Horn                      => 'Horn',
				\Midi\Util\Instrument::BrassSection              => 'Brass Section',
				\Midi\Util\Instrument::SynthesizerBrass1         => 'Synthesizer Brass 1',
				\Midi\Util\Instrument::SynthesizerBrass2         => 'Synthesizer Brass 2',
				\Midi\Util\Instrument::SopranoSaxophone          => 'Soprano Saxophone',
				\Midi\Util\Instrument::AltoSaxophone             => 'Alto Saxophone',
				\Midi\Util\Instrument::TenorSaxophone            => 'Tenor Saxophone',
				\Midi\Util\Instrument::BaritoneSaxophone         => 'Baritone Saxophone',
				\Midi\Util\Instrument::Oboe                      => 'Oboe',
				\Midi\Util\Instrument::EnglishHorn               => 'English Horn',
				\Midi\Util\Instrument::Bassoon                   => 'Bassoon',
				\Midi\Util\Instrument::Clarinet                  => 'Clarinet',
				\Midi\Util\Instrument::PiccoloFlute              => 'Piccolo Flute',
				\Midi\Util\Instrument::Flute                     => 'Flute',
				\Midi\Util\Instrument::Recorder                  => 'Recorder',
				\Midi\Util\Instrument::PanPipes                  => 'Pan Pipes',
				\Midi\Util\Instrument::BottleBlow                => 'Bottle Blow',
				\Midi\Util\Instrument::Shakuhachi                => 'Shakuhachi',
				\Midi\Util\Instrument::Whistle                   => 'Whistle',
				\Midi\Util\Instrument::Ocarina                   => 'Ocarina',
				\Midi\Util\Instrument::SquareSynth               => 'Square (synth)',
				\Midi\Util\Instrument::SawToothSynth             => 'Saw Tooth (synth)',
				\Midi\Util\Instrument::CaliopeSynth              => 'Caliope (synth)',
				\Midi\Util\Instrument::ChiffSynth                => 'Chiff (synth)',
				\Midi\Util\Instrument::CharangSynth              => 'Charang (synth)',
				\Midi\Util\Instrument::VoiceSynth                => 'Voice (synth)',
				\Midi\Util\Instrument::FifthSynth                => 'Fifth (synth)',
				\Midi\Util\Instrument::BrassLeadSynth            => 'Brass+Lead (synth)',
				\Midi\Util\Instrument::NewAgeSynthPad            => 'New Age (synth pad)',
				\Midi\Util\Instrument::WarmSynthPad              => 'Warm (synth pad)',
				\Midi\Util\Instrument::PolysynthSynthPad         => 'Polysynth (synth pad)',
				\Midi\Util\Instrument::ChoirSynthPad             => 'Choir (synth pad)',
				\Midi\Util\Instrument::BowedSynthPad             => 'Bowed (synth pad)',
				\Midi\Util\Instrument::MetallicSynthPad          => 'Metallic (synth pad)',
				\Midi\Util\Instrument::HaloSynthPad              => 'Halo (synth pad)',
				\Midi\Util\Instrument::SweepSynthPad             => 'Sweep (synth pad)',
				\Midi\Util\Instrument::RainSynthEffect           => 'Rain (synth effect)',
				\Midi\Util\Instrument::SoundtrackSynthEffect     => 'Soundtrack (synth effect)',
				\Midi\Util\Instrument::CrystalSynthEffect        => 'Crystal (synth effect)',
				\Midi\Util\Instrument::AtmosphereSynthEffect     => 'Atmosphere (synth effect)',
				\Midi\Util\Instrument::BrightnessSynthEffect     => 'Brightness (synth effect)',
				\Midi\Util\Instrument::GoblinsSynthEffect        => 'Goblins (synth effect)',
				\Midi\Util\Instrument::EchoesSynthEffect         => 'Echoes (synth effect)',
				\Midi\Util\Instrument::SciFiSynthEffect          => 'Sci Fi (synth effect)',
				\Midi\Util\Instrument::Sitar                     => 'Sitar',
				\Midi\Util\Instrument::Banjo                     => 'Banjo',
				\Midi\Util\Instrument::Shamisen                  => 'Shamisen',
				\Midi\Util\Instrument::Koto                      => 'Koto',
				\Midi\Util\Instrument::Kalimba                   => 'Kalimba',
				\Midi\Util\Instrument::Bagpipe                   => 'Bagpipe',
				\Midi\Util\Instrument::Fiddle                    => 'Fiddle',
				\Midi\Util\Instrument::Shanai                    => 'Shanai',
				\Midi\Util\Instrument::TinkleBell                => 'Tinkle Bell',
				\Midi\Util\Instrument::Agogo                     => 'Agogo',
				\Midi\Util\Instrument::SteelDrum                 => 'Steel Drum',
				\Midi\Util\Instrument::Woodblock                 => 'Woodblock',
				\Midi\Util\Instrument::Taikodrum                 => 'Taiko-drum',
				\Midi\Util\Instrument::MelodicTom                => 'Melodic Tom',
				\Midi\Util\Instrument::SynthesizedDrum           => 'Synthesized Drum',
				\Midi\Util\Instrument::CymbalHiHat               => 'Cymbal Hi-Hat',
				\Midi\Util\Instrument::GuitarFretNoise           => 'Guitar Fret Noise',
				\Midi\Util\Instrument::BreathNoise               => 'Breath Noise',
				\Midi\Util\Instrument::Seashore                  => 'Seashore',
				\Midi\Util\Instrument::BirdSong                  => 'Bird Song',
				\Midi\Util\Instrument::TelephoneRing             => 'Telephone Ring',
				\Midi\Util\Instrument::Helicopter                => 'Helicopter',
				\Midi\Util\Instrument::Applause                  => 'Applause',
				\Midi\Util\Instrument::Gunshot                   => 'Gunshot'
			);
			
			foreach ($instrumentMap as $instrument => $name) {
				$this->assertEquals(\Midi\Util\Instrument::getInstrumentName($instrument), $name);
			}
		}

	}

?>